FROM rocm/dev-ubuntu-22.04:latest

ENV DEBIAN_FRONTEND noninteractive
RUN chmod 1777 /tmp

WORKDIR /home/

# install dependencies
RUN apt-get update && \
    apt-get install -y \
       	wget \
	    git \
        vim \
	    build-essential \
	    libboost-all-dev \
		libtbb-dev \
	    cmake && \
	apt-get clean

# Clone and install DIPPER inside the dipper environment
RUN wget https://github.com/TurakhiaLab/DIPPER/archive/refs/tags/v0.1.3.tar.gz && \
    tar -xzf v0.1.3.tar.gz && \
    mv DIPPER-0.1.3 DIPPER && \
    rm v0.1.3.tar.gz
    cd /home/DIPPER/install && \
    ./installDIPPER.sh hip

ENV PATH="/home/DIPPER/bin:$PATH"

CMD ["/bin/bash"]